### ISSUE TITLE
Old gem version on Rubygems

### ISSUE THREAD

**Issue by bryszard** [perfectline/validates_url#102]
As I'm updating my app to Ruby 2.7.0 I'm getting deprecation warnings about `URI.escape` being used in the `validates_url` gem.

I can see that on the master branch you've already fixed that problem, but there is no new version of gem available on Rubygems.

When can we expect new version of the gem to be published?

**Comment by NDuggan** [comment]
@kritik sorry if you're the wrong person to mention but you seem the most active on the recent commits. Any movement on this?

**Comment by kritik** [comment]
@NDuggan sorry, for long response. I'm the right person. If someone makes pull request I will merge it.

**Comment by NDuggan** [comment]
@kritik no need to apologise, thanks for getting back to me.

What do you need me to do as the fix is already merged into master and it also looks like the last 2 versions on Rubygems haven't been published to GitHub either (v1.0.6 and v1.0.8 respectively), as tags at least. `VERSION.yml` has been updated, but it's not listed as a release on GitHub.

I'm currently pointing to the commit ref just to get around it…

**Comment by kritik** [comment]
@NDuggan just do updates and make a pull request

**Comment by airled** [comment]
@NDuggan I think, you forgot to bump version in [gemspec](https://github.com/perfectline/validates_url/blob/master/validate_url.gemspec).

**Comment by NDuggan** [comment]
@airled you're absolutely right, sorry this is the first time I've tried to update a public gem. I was just trying to bump it like the previous version bump (which probably done the same as I did).

I am getting a lot of `freeze` changes, though. Should I be building with a specific version of Ruby as well?

**Example**

```git
-  s.name = "validate_url"
-  s.version = "1.0.8"
+  s.name = "validate_url".freeze
+  s.version = "1.0.9"
```

**Comment by airled** [comment]
@NDuggan As far as I understand, gem was build with `Jeweler`. [Here](https://github.com/perfectline/validates_url/blob/master/validate_url.gemspec#L1) is the line about it, so it's better to use this tool.

**Comment by NDuggan** [comment]
@airled yeah that's what I read and then used (the rake commands), but didn't want to send a PR will loads of `.freeze` changes and break the gem for everyone for a minor version 🙈

**Comment by airled** [comment]
@NDuggan I tried it by myself. Yes, it add `freeze` everywhere moreove it breaks gemspec file. Try to run `bundle exec rake -T` after `bundle exec rake gemspec`.
My log:
```
[~/validates_url] > be rake gemspec                                                                  (master|✔)[14:29:27][air@air-e11]
Generated: validate_url.gemspec
validate_url.gemspec is valid.
[~/validates_url] > be rake -T                                                                      (master|✚1)[14:29:30][air@air-e11]
bundler: failed to load command: rake (/home/air/.asdf/installs/ruby/2.5.8/bin/rake)
Gem::InvalidSpecificationException: The gemspec at /home/air/validates_url/validate_url.gemspec is not valid. Please fix this gemspec.
The validation error was 'duplicate dependency on rspec (>= 0, development), (>= 0) use:
    add_development_dependency 'rspec', '>= 0', '>= 0'
duplicate dependency on diff-lcs (>= 1.1.2, development), (>= 1.1.2) use:
    add_development_dependency 'diff-lcs', '>= 1.1.2', '>= 1.1.2'
'

  /home/air/.asdf/installs/ruby/2.5.8/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/rubygems_integration.rb:65:in `rescue in validate'
  /home/air/.asdf/installs/ruby/2.5.8/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/rubygems_integration.rb:60:in `validate'
  /home/air/.asdf/installs/ruby/2.5.8/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/source/path.rb:157:in `validate_spec'
  /home/air/.asdf/installs/ruby/2.5.8/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/source/path.rb:171:in `block in load_spec_files'
  /home/air/.asdf/installs/ruby/2.5.8/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/source/path.rb:165:in `each'
  /home/air/.asdf/installs/ruby/2.5.8/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/source/path.rb:165:in `load_spec_files'
  /home/air/.asdf/installs/ruby/2.5.8/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/source/path.rb:100:in `local_specs'
  /home/air/.asdf/installs/ruby/2.5.8/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/source/path.rb:108:in `specs'
  /home/air/.asdf/installs/ruby/2.5.8/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/definition.rb:590:in `specs_for_source_changed?'
  /home/air/.asdf/installs/ruby/2.5.8/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/definition.rb:575:in `specs_changed?'
  /home/air/.asdf/installs/ruby/2.5.8/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/definition.rb:619:in `block in converge_paths'
  /home/air/.asdf/installs/ruby/2.5.8/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/definition.rb:618:in `any?'
  /home/air/.asdf/installs/ruby/2.5.8/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/definition.rb:618:in `converge_paths'
  /home/air/.asdf/installs/ruby/2.5.8/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/definition.rb:120:in `initialize'
  /home/air/.asdf/installs/ruby/2.5.8/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/dsl.rb:218:in `new'
  /home/air/.asdf/installs/ruby/2.5.8/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/dsl.rb:218:in `to_definition'
  /home/air/.asdf/installs/ruby/2.5.8/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/dsl.rb:13:in `evaluate'
  /home/air/.asdf/installs/ruby/2.5.8/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/definition.rb:35:in `build'
  /home/air/.asdf/installs/ruby/2.5.8/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/lib/bundler.rb:135:in `definition'
  /home/air/.asdf/installs/ruby/2.5.8/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/lib/bundler.rb:101:in `setup'
  /home/air/.asdf/installs/ruby/2.5.8/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/setup.rb:10:in `<top (required)>'
  /home/air/.asdf/installs/ruby/2.5.8/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  /home/air/.asdf/installs/ruby/2.5.8/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
```
Do you have it too?

**Comment by NDuggan** [comment]
@airled yes I get the exact same…

**Comment by airled** [comment]
@kritik Need your inspection. Jeweler generates invalid gemspec so we can't update gemspec file properly. Could you check it please?

**Comment by kritik** [comment]
so, you want to publish new version. Ok, I can do that. But what's about URI.escape? Did anyone update code to support that?

**Comment by airled** [comment]
@kritik @bryszard at the top post says:

> As I'm updating my app to Ruby 2.7.0 I'm getting deprecation warnings about URI.escape being used in the validates_url gem. I can see that on the master branch you've already fixed that problem, but there is no new version of gem available on Rubygems.

As far as I undestand master branch already has that fixes. Last update of the [gem](https://rubygems.org/gems/validate_url) on rubygems was almost year ago (on april 2019). Thats why we are asking you to just push new version there.

**Comment by NDuggan** [comment]
@kritik @airled correct, the code is already on `master` for `URI.escape` (1945ae414dd64490addf456565e295995e92d07e and maybe 3dde8639a29492725505762cf5a86df9e14d5861 too).

We literally just wanted an official version pushed to Rubygems.

**Comment by kritik** [comment]
pushed new version
