### ISSUE TITLE
Version 1.0.10 has dependency loop

### ISSUE THREAD

**Issue by Liquidsoul** [perfectline/validates_url#104]
Tried to bundle using `gem 'validate_url', '1.0.10'` and bundler failed with error:

    Your bundle requires gems that depend on each other, creating an infinite loop. Please remove gem 'validate_url' and try again.

**Comment by kritik** [comment]
@Liquidsoul try now

**Comment by Liquidsoul** [comment]
Works with version `1.0.11`. Thank you fixing this quickly 👍
