### ISSUE TITLE
Set up a CI for Pull Requests

### ISSUE THREAD

**Issue by olleolleolle** [perfectline/validates_url#120]
It seems this repository has a configuration file for Travis CI, but no hooks are firing.

So, this Issue is about having a CI which runs on pull reqeusts and pushes.

Here's one example: https://schneems.com/2021/01/13/migrating-a-ruby-library-from-travisci-to-circleci/

**Comment by kritik** [comment]
why to move to circleci?

**Comment by olleolleolle** [comment]
@kritik Any other provider which offers free builds for Open Source projects is fine. The example above is just one. 

Here's an example Issue & PR which made the move for another project: https://github.com/simi/omniauth-facebook/issues/349

**Comment by kritik** [comment]
why not Travis CI?

**Comment by olleolleolle** [comment]
@kritik Since the close of 2020, they no longer supply free build minutes to Open Source projects. https://twitter.com/james_hilliard/status/1336081776691843072 Example tweet from a maintainer, reacting to that.

**Comment by olleolleolle** [comment]
Also, I fail to find any "mark" on individual commits that they have run any CI webhooks (a green or red dot, next to the commit, you know).

**Comment by kritik** [comment]
>Since the close of 2020, they no longer supply free build minutes

I see your point

>a green or red dot, next to the commit, you know

me neither ;)
