### ISSUE TITLE
Release to Rubygems?

### ISSUE THREAD

**Issue by fredngo** [perfectline/validates_url#27]
Hi, can we have a new release to Rubygems so that the :no_local option is available?

I know that I can use the latest github version like:

```
gem 'validate_url', github: 'perfectline/validates_url'
```
BUT for me, the problem is I am writing a gem and I cannot embed a github reference into a gemspec!

All dependencies in a gem must be released -- See http://stackoverflow.com/questions/6499410/ruby-gemspec-dependency-is-possible-have-a-git-branch-dependency

Thanks in advance!

**Comment by tinynumbers** [comment]
Agreed, it would be great to get the `no_local` option into the released version of this gem.   Thanks!

**Comment by nevesenin** [comment]
+1

**Comment by johanness** [comment]
:+1:

**Comment by kritik** [comment]
new release has been shipped. Thanks for pushing ;)

**Comment by fredngo** [comment]
Thanks!

**Comment by johanness** [comment]
Great job!
