### ISSUE TITLE
This gem pass URLs with spaces in domain name

### ISSUE THREAD

**Issue by dobryakov** [perfectline/validates_url#34]
"http://www.example com" is VALID url for this gem.

**Comment by kritik** [comment]
actually that's a valid url by standard

**Comment by mezza** [comment]
err, don't think so. In either case, updating addressable and requiring it to be at least 2.4.0 fixes this.

**Comment by andresilveira** [comment]
+1 for updating dependencies :)

**Comment by kritik** [comment]
pull request is always welcome

**Comment by vidoseaver** [comment]
@kritik is this project still alive? if so is this an issue you'd still want a pr on?

**Comment by kritik** [comment]
Yes, we're still using this project and I've never faced problem that users are inserting domain like you have. But if you make pull request, I'll merge it
