### ISSUE TITLE
Release Version

### ISSUE THREAD

**Issue by ishields** [perfectline/validates_url#61]
Hello!  I was interested in using this gem however I noticed there hasn't been a release since July 2015.  I noticed there have been recent commits so I'm curious whether master is stable.  Does it make sense to increase the release version?

**Comment by aleksandrs-ledovskis** [comment]
Ping @kritik

**Comment by kritik** [comment]
@ishields @aleksandrs-ledovskis yes, master is very stable

**Comment by aleksandrs-ledovskis** [comment]
@kritik I would ask you to reconsider and release a new version.

One issue with having a gem live in `master`-only state is that in Rails engine `gemspec`'s we cannot specify "git" source.

It would be helpful to have a new `validates_url` gem's version appear on Rubygems. Especially, as after https://github.com/perfectline/validates_url/pull/57 it may work differently in `v1.0.2` vs. `master`

**Comment by aleksandrs-ledovskis** [comment]
@kritik Pinging once more. 

Thank you for maintaining the gem and making sure the `master` version is stable.
However, could you share you view on topic of Rails engine usage/version discrepancies?

**Comment by kritik** [comment]
@aleksandrs-ledovskis @ishields Finally I pushed new version of this gem

**Comment by aleksandrs-ledovskis** [comment]
Great news. Much appreciated!
