### ISSUE TITLE
url without domain is valid

### ISSUE THREAD

**Issue by greggzst** [perfectline/validates_url#62]
When I type url like this: `http://ssds` validator says it is valid but it's not. 
There are no url like this, there is no `http://google`.

Hope you can fix it.

**Comment by kritik** [comment]
There can be url like "ssds". First example is localhost ;)

**Comment by greggzst** [comment]
@kritik True I forgot about that ;) But is there a way to prevent user from entering url that doesn't make sense like 'sdsa'?
