### ISSUE TITLE
Use validate url as a callback

### ISSUE THREAD

**Issue by misner** [perfectline/validates_url#66]
I need to use validate_url as a callback on various object lifefecyle such as after_update or after_validation.

Is it possible to use it as callback and what's the proper way to do it? Could not find it in the official documentation.

Thanks

**Comment by kritik** [comment]
What do you want to do exactly?

**Comment by misner** [comment]
sure, let me give you the use case.

I noticed validates url:true works for basic url field in my Active Admin panel but no in this case:
I have a Deal model. In this Deal Model, I have a field receving "raw data called raw_data

Deal1.raw_data = ["data1", "data2", "data3"...]

Another Deal attribute takes this data to create the value of another attribute called fg_og_url with the "data" of the above array as parameters.

When I create or edit a Deal, the following actions take place:

```
before_create :set_fb_og_url
before_update :set_fb_og_url

def set_fb_og_url
      self.fb_og_url = "http://wwwfb_og.com"+raw_data[0]+"supertext/fghufghuf"+raw_data[1]+"supertoo"+raw_data[2]
end

```
Today I have 
```
validates :fb_og_url,
              presence: true,
              url: true
```

but it does not work. For example if I add an empty space inside the url, it does not reject the create/edit

I have the feeling the reasons is the ORDER between

- the moment the app executes the callback set_fb_og_url and

- the moment the app executes the validates :fb_og_url, url :true

Hence I am looking into ordering them explictily one to another like
`before_update :set_fb_og_url, : VALIDATE_AS_CALLBACK `

...as they will be performed by rails in this order

That's my main assumption for the bug so trying to roder them could rule this asusmption out or validate it!:)

So that's why I would like to know if I can use the gem not in validate: url true but as a callback

**Comment by kritik** [comment]
```
before_create :set_fb_og_url
before_update :set_fb_og_url
```
Is not you case. Use before_validation. [Here's](http://api.rubyonrails.org/classes/ActiveRecord/Callbacks.html) an ordered list of callbacks and actions which are called during save.

**Comment by kritik** [comment]
```
before_create :set_fb_og_url
before_update :set_fb_og_url
```
Is not you case. Use before_validation. [Here's](http://api.rubyonrails.org/classes/ActiveRecord/Callbacks.html) an ordered list of callbacks and actions which are called during save.

**Comment by misner** [comment]
I'll give it a try but I think during my bug-fixing hours yesterday I already tried it. thanks for the tip:)

**Comment by kritik** [comment]
that's how rails should be working.

**Comment by misner** [comment]
thanks, working indeed ! Weird it failed yesterday:(
