### ISSUE TITLE
warning: URI.escape is obsolete

### ISSUE THREAD

**Issue by lostie** [perfectline/validates_url#92]
Using the latest ruby version 2.7, I get the following warning:

```ruby
lib/validate_url.rb:23: warning: URI.escape is obsolete
```

Is this likely to break if ruby decides to remove the method altogether?

**Comment by oshow** [comment]
it seems #85 removes `URI.escape`.

**Comment by kritik** [comment]
Just merged that pull request. Should be better.

**Comment by xtagon** [comment]
I'm seeing this error on Ruby 2.7 with validates_url 1.0.8. Any chance we could get a 1.0.9 gem release?

Thanks for fixing this 👍
